---

- hosts: all

  tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400 #One day
            
      - name: Install base packages
        apt: name={{ item }} state=installed
        with_items:
            - git
            - htop
            - screen
        tags:
            - packages
      
      
      - name: Install Anaconda
        block:
            - name: Download Anaconda
              get_url: 
                url: https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
                dest: /tmp/anaconda.sh
                mode: 0550

            - name: Run the installer
              shell: /tmp/anaconda.sh -b -u -p /home/ubuntu/anaconda

            - name: Remove the installer
              file:
                state: absent
                path: /tmp/anaconda.sh

            - name: Add Conda bin to path
              become: True
              shell: echo 'export PATH=/home/ubuntu/anaconda/bin:$PATH' >> .bashrc

      - name: Transfer Cuda Script
        copy:
            src: cuda-install.sh 
            dest: /home/ubuntu/cuda-install.sh
            mode: 0600

      - name: Transfer Kaggle
        copy:
            src: /Users/kkalyan/.kaggle.json
            dest: ~/.kaggle/kaggle.json
            mode: 0600

      - name: Execute the script
        command: sh /home/ubuntu/cuda-install.sh
            
      - name: Install Pip
        become: True
        shell: conda install -y pip

      - name: Install PyTorch
        become: True
        shell: conda install pytorch torchvision cudatoolkit=10.0 -c pytorch-nightly
